"use client";

import { useCallback, useEffect, useRef, useState } from "react";

type GameState = "ready" | "playing" | "paused" | "over";
type Item = { id: number; lane: number; z: number; type: "coin" | "sign" | "jump" | "duck"; word?: string; collected?: boolean };
const LANES = [-1, 0, 1];
const SIGNS = ["HOLA", "GRACIAS", "AMISTAD", "ECUADOR", "APRENDER"];
const GESTURES: Record<string, string> = { HOLA: "👋", GRACIAS: "🤲", AMISTAD: "🤝", ECUADOR: "🫶", APRENDER: "👐" };

export default function Home() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const gameRef = useRef({ state: "ready" as GameState, lane: 0, playerX: 0, jump: 0, jumpV: 0, duck: 0, score: 0, coins: 0, signs: 0, distance: 0, speed: .42, items: [] as Item[], spawn: 28, nextId: 1, flash: 0, lastSign: "", time: 0 });
  const [ui, setUi] = useState({ state: "ready" as GameState, score: 0, coins: 0, signs: 0, speed: 1 });
  const sync = useCallback(() => { const g = gameRef.current; setUi({ state: g.state, score: Math.floor(g.score), coins: g.coins, signs: g.signs, speed: Math.round(g.speed / .042) / 10 }); }, []);
  const start = useCallback(() => { Object.assign(gameRef.current, { state: "playing", lane: 0, playerX: 0, jump: 0, jumpV: 0, duck: 0, score: 0, coins: 0, signs: 0, distance: 0, speed: .42, items: [], spawn: 15, flash: 0, lastSign: "", time: 0 }); sync(); }, [sync]);
  const action = useCallback((kind: "left" | "right" | "jump" | "duck" | "pause") => { const g = gameRef.current; if (kind === "pause") { if (g.state === "playing") g.state = "paused"; else if (g.state === "paused") g.state = "playing"; sync(); return; } if (g.state !== "playing") return; if (kind === "left") g.lane = Math.max(-1, g.lane - 1); if (kind === "right") g.lane = Math.min(1, g.lane + 1); if (kind === "jump" && g.jump === 0) g.jumpV = 9.5; if (kind === "duck" && g.jump === 0) g.duck = 35; }, [sync]);

  useEffect(() => { const onKey = (e: KeyboardEvent) => { const map: Record<string, "left" | "right" | "jump" | "duck" | "pause"> = { ArrowLeft: "left", a: "left", A: "left", ArrowRight: "right", d: "right", D: "right", ArrowUp: "jump", w: "jump", W: "jump", " ": "jump", ArrowDown: "duck", s: "duck", S: "duck", p: "pause", P: "pause", Escape: "pause" }; if (map[e.key]) { e.preventDefault(); action(map[e.key]); } if (e.key === "Enter" && gameRef.current.state !== "playing") start(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [action, start]);

  useEffect(() => {
    const canvas = canvasRef.current!, ctx = canvas.getContext("2d")!; let frame = 0, last = performance.now(), uiTick = 0;
    const resize = () => { const dpr = Math.min(devicePixelRatio, 2), r = canvas.getBoundingClientRect(); canvas.width = r.width * dpr; canvas.height = r.height * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); }; resize(); window.addEventListener("resize", resize);
    function draw(now: number) {
      const dt = Math.min((now - last) / 16.667, 2); last = now; const w = canvas.clientWidth, h = canvas.clientHeight, g = gameRef.current;
      if (g.state === "playing") {
        g.time += dt; g.distance += g.speed * dt; g.score += g.speed * .24 * dt; g.speed = Math.min(.86, .42 + g.distance / 9000); g.playerX += (g.lane - g.playerX) * .2 * dt;
        if (g.jumpV || g.jump > 0) { g.jumpV -= .65 * dt; g.jump = Math.max(0, g.jump + g.jumpV * dt); if (g.jump === 0) g.jumpV = 0; } if (g.duck > 0) g.duck -= dt; if (g.flash > 0) g.flash -= dt; g.spawn -= g.speed * dt;
        if (g.spawn <= 0) { const lane = LANES[Math.floor(Math.random() * 3)], r = Math.random(); const type: Item["type"] = r < .43 ? "coin" : r < .58 ? "sign" : r < .79 ? "jump" : "duck"; const word = type === "sign" ? SIGNS[Math.floor(Math.random() * SIGNS.length)] : undefined; g.items.push({ id: g.nextId++, lane, z: 105, type, word }); if (Math.random() < .32 && !["jump", "duck"].includes(type)) g.items.push({ id: g.nextId++, lane, z: 118, type: "coin" }); g.spawn = 20 + Math.random() * 14; }
        for (const item of g.items) { item.z -= g.speed * 2.05 * dt; if (!item.collected && item.z < 8 && item.z > -2 && item.lane === g.lane) { if (item.type === "coin") { item.collected = true; g.coins++; g.score += 25; } else if (item.type === "sign") { item.collected = true; g.signs++; g.score += 100; g.lastSign = item.word!; g.flash = 75; } else if ((item.type === "jump" && g.jump < 34) || (item.type === "duck" && g.duck <= 0)) g.state = "over"; } }
        g.items = g.items.filter(i => i.z > -5 && !i.collected); if (++uiTick % 8 === 0) sync();
      }
      const horizon = h * .27, bottom = h * .96, sky = ctx.createLinearGradient(0, 0, 0, horizon); sky.addColorStop(0, "#7d62ff"); sky.addColorStop(1, "#c7a8ff"); ctx.fillStyle = sky; ctx.fillRect(0, 0, w, horizon); ctx.fillStyle = "#44328c"; ctx.beginPath(); ctx.moveTo(0, horizon); for (let x = 0; x <= w; x += 45) ctx.lineTo(x, horizon - 25 - Math.sin(x * .025) * 25); ctx.lineTo(w, horizon); ctx.fill(); ctx.fillStyle = "#efc75e"; ctx.beginPath(); ctx.arc(w * .78, horizon * .42, 26, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = "#201a3a"; ctx.beginPath(); ctx.moveTo(w * .35, horizon); ctx.lineTo(w * .65, horizon); ctx.lineTo(w * .92, bottom); ctx.lineTo(w * .08, bottom); ctx.closePath(); ctx.fill(); ctx.strokeStyle = "rgba(255,255,255,.28)"; ctx.lineWidth = 2; for (const lane of [-.5, .5]) { ctx.beginPath(); ctx.moveTo(w * .5 + lane * w * .06, horizon); ctx.lineTo(w * .5 + lane * w * .27, bottom); ctx.stroke(); } for (let z = 0; z < 100; z += 12) { const p = ((z - g.distance * 2) % 100 + 100) % 100 / 100, y = horizon + (bottom - horizon) * p * p, roadW = w * (.15 + .75 * p); ctx.strokeStyle = "rgba(255,255,255,.09)"; ctx.beginPath(); ctx.moveTo(w / 2 - roadW / 2, y); ctx.lineTo(w / 2 + roadW / 2, y); ctx.stroke(); }
      const project = (lane: number, z: number) => { const p = Math.max(0, 1 - z / 110), s = .24 + p * .9; return { x: w / 2 + lane * w * (.075 + p * .21), y: horizon + (bottom - horizon) * p * p, s }; };
      [...g.items].sort((a, b) => b.z - a.z).forEach(item => { const p = project(item.lane, item.z); if (item.z > 110) return; ctx.save(); ctx.translate(p.x, p.y); ctx.scale(p.s, p.s); if (item.type === "coin") { ctx.fillStyle = "#ffd84a"; ctx.beginPath(); ctx.arc(0, -24, 15, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = "#fff1a4"; ctx.lineWidth = 4; ctx.stroke(); ctx.fillStyle = "#7a4b00"; ctx.font = "bold 16px Arial"; ctx.textAlign = "center"; ctx.fillText("S", 0, -18); } if (item.type === "sign") { ctx.fillStyle = "#ff4d8d"; ctx.beginPath(); ctx.roundRect(-27, -55, 54, 54, 12); ctx.fill(); ctx.fillStyle = "white"; ctx.font = "28px Arial"; ctx.textAlign = "center"; ctx.fillText(GESTURES[item.word!] || "👐", 0, -20); } if (item.type === "jump") { ctx.fillStyle = "#ff6b35"; ctx.beginPath(); ctx.roundRect(-34, -30, 68, 30, 6); ctx.fill(); ctx.fillStyle = "#ffe8c8"; ctx.fillRect(-26, -23, 52, 7); } if (item.type === "duck") { ctx.fillStyle = "#34d2bc"; ctx.fillRect(-42, -82, 84, 18); ctx.fillStyle = "#154d52"; ctx.fillRect(-42, -64, 9, 64); ctx.fillRect(33, -64, 9, 64); } ctx.restore(); });
      const px = w / 2 + g.playerX * w * .27, py = bottom - 42 - g.jump; ctx.save(); ctx.translate(px, py); if (g.duck > 0) { ctx.scale(1, .62); ctx.translate(0, 23); } ctx.shadowColor = "rgba(0,0,0,.35)"; ctx.shadowBlur = 14; ctx.fillStyle = "#ffcf3f"; ctx.beginPath(); ctx.arc(0, -48, 18, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#ff4d8d"; ctx.beginPath(); ctx.roundRect(-22, -33, 44, 54, 14); ctx.fill(); ctx.strokeStyle = "#f7f3ff"; ctx.lineWidth = 8; ctx.beginPath(); ctx.moveTo(-12, 16); ctx.lineTo(-17, 40); ctx.moveTo(12, 16); ctx.lineTo(17, 40); ctx.stroke(); ctx.shadowBlur = 0; ctx.fillStyle = "#221d44"; ctx.beginPath(); ctx.arc(-6, -51, 2, 0, 7); ctx.arc(6, -51, 2, 0, 7); ctx.fill(); ctx.restore();
      if (g.flash > 0) { const a = Math.min(1, g.flash / 15); ctx.fillStyle = `rgba(24,20,49,${.82 * a})`; ctx.beginPath(); ctx.roundRect(w / 2 - 120, h * .32, 240, 120, 22); ctx.fill(); ctx.fillStyle = "white"; ctx.textAlign = "center"; ctx.font = "38px Arial"; ctx.fillText(GESTURES[g.lastSign] || "👐", w / 2, h * .32 + 48); ctx.font = "800 20px Arial"; ctx.fillText(g.lastSign, w / 2, h * .32 + 82); ctx.font = "12px Arial"; ctx.fillStyle = "#d6ceff"; ctx.fillText("GESTO ILUSTRATIVO · +100", w / 2, h * .32 + 104); }
      frame = requestAnimationFrame(draw);
    }
    frame = requestAnimationFrame(draw); return () => { cancelAnimationFrame(frame); window.removeEventListener("resize", resize); };
  }, [sync]);

  const overlay = ui.state !== "playing";
  return <main className="shell"><header className="topbar"><div className="brand"><span className="brandMark">SR</span><span>Sign<span>Rush</span></span></div><div className="tagline">Corre · aprende · repite</div><button className="sound" onClick={() => action("pause")} aria-label={ui.state === "paused" ? "Reanudar" : "Pausar"}>{ui.state === "paused" ? "▶" : "Ⅱ"}</button></header><section className="gameWrap"><div className="hud"><div><small>PUNTOS</small><strong>{ui.score.toLocaleString("es-EC")}</strong></div><div><small>MONEDAS</small><strong>◉ {ui.coins}</strong></div><div><small>SEÑAS</small><strong>👐 {ui.signs}</strong></div><div><small>RITMO</small><strong>{ui.speed}×</strong></div></div><canvas ref={canvasRef} aria-label="Pista de SignRush con tres carriles" />{overlay && <div className="overlay"><div className="panel">{ui.state === "ready" ? <><span className="eyebrow">APRENDE EN MOVIMIENTO</span><h1>¡La pista te espera!</h1><p>Cambia de carril, supera obstáculos y colecciona fichas de señas.</p><div className="how"><span>← →<small>MOVER</small></span><span>↑<small>SALTAR</small></span><span>↓<small>AGACHARSE</small></span></div><button onClick={start}>EMPEZAR CARRERA <b>→</b></button></> : ui.state === "paused" ? <><span className="eyebrow">PAUSA</span><h1>Toma aire</h1><p>Tu carrera está esperando.</p><button onClick={() => action("pause")}>CONTINUAR <b>▶</b></button></> : <><span className="eyebrow">FIN DE LA CARRERA</span><h1>¡Buen intento!</h1><div className="results"><span><small>PUNTOS</small>{ui.score}</span><span><small>SEÑAS</small>{ui.signs}</span></div><button onClick={start}>VOLVER A CORRER <b>↻</b></button></>}</div></div>}<div className="mobileControls"><button onPointerDown={() => action("left")} aria-label="Mover a la izquierda">←</button><button onPointerDown={() => action("jump")} aria-label="Saltar">↑</button><button onPointerDown={() => action("duck")} aria-label="Agacharse">↓</button><button onPointerDown={() => action("right")} aria-label="Mover a la derecha">→</button></div></section><footer><span><i className="dot pink" /> Fichas = 100 puntos</span><span><i className="dot gold" /> Monedas = 25 puntos</span><span className="notice">Animaciones ilustrativas. No sustituyen enseñanza validada de LSE.</span></footer></main>;
}
